export interface drinks {
  drinks?: (DrinksEntity)[] | null;
}
export interface DrinksEntity {
  idDrink: string;
  strDrink: string;
  strDrinkAlternate?: null;
  strTags?: null;
  strVideo?: null;
  strCategory: string;
  strIBA?: null;
  strAlcoholic: string;
  strGlass: string;
  strInstructions: string;
  strInstructionsES?: null;
  strInstructionsDE: string;
  strInstructionsFR?: null;
  strInstructionsIT: string;
  strDrinkThumb: string;
  strIngredient1: string;
  strIngredient2: string;
  strIngredient3?: string | null;
  strIngredient4?: string | null;
  strIngredient5?: string | null;
  strIngredient6?: string | null;
  strIngredient7?: string | null;
  strIngredient8?: null;
  strIngredient9?: null;
  strIngredient10?: null;
  strIngredient11?: null;
  strIngredient12?: null;
  strIngredient13?: null;
  strIngredient14?: null;
  strIngredient15?: null;
  strMeasure1: string;
  strMeasure2?: string | null;
  strMeasure3?: string | null;
  strMeasure4?: string | null;
  strMeasure5?: string | null;
  strMeasure6?: string | null;
  strMeasure7?: string | null;
  strMeasure8?: null;
  strMeasure9?: null;
  strMeasure10?: null;
  strMeasure11?: null;
  strMeasure12?: null;
  strMeasure13?: null;
  strMeasure14?: null;
  strMeasure15?: null;
  strImageSource?: string | null;
  strImageAttribution?: null;
  strCreativeCommonsConfirmed: string;
  dateModified?: string | null;
}
